---

- name: "Check Auth Key Information : {{ user_key.username }}"
  assert:
    that:
     - (user_key.key_file is defined) != (user_key.key_content is defined)
    msg: "One and only one of ssh_authorized_keys.*.key_file or ssh_authorized_keys.*.key_content must be defined."
  tags: ssh-keys

- name: "Get User Information : {{ user_key.username }}"
  getent:
    database: passwd
    key:      "{{ user_key.username }}"
  tags: ssh-keys

- name: "Build Information : {{ user_key.username }}"
  set_fact:
    authkeys_file: "{{ user_key.authkeys_file | default(ssh_authkeys_files | first) | authfile_replace(getent_passwd) }}"
    is_local:      "{{ user_key.authkeys_file | default(ssh_authkeys_files | first) | is_local_path }}"
  tags: ssh-keys

- name: "Authorize Key from File : {{ user_key.username }}"
  become_user: "{{ user_key.username }}"
  authorized_key:
    user:  "{{ user_key.username }}"
    state: "{{ user_key.state | default(omit) }}"
    key:   "{{ lookup('file', user_key.key_file) }}"
    path:  "{{ authkeys_file }}"
    key_options: "{{ user_key.key_options | default(omit) }}"
    manage_dir: no
  when: user_key.key_file is defined
  tags: ssh-keys

- name: "Authorize Key from Content : {{ user_key.username }}"
  become_user: "{{ user_key.username }}"
  authorized_key:
    user:  "{{ user_key.username }}"
    state: "{{ user_key.state | default(omit) }}"
    key:   "{{ user_key.key_content }}"
    path:  "{{ authkeys_file }}"
    key_options: "{{ user_key.key_options | default(omit) }}"
    manage_dir: no
  when: user_key.key_content is defined
  tags: ssh-keys

- name: "Set Ownership for Global File : {{ user_key.username }}"
  file: path="{{ authkeys_file }}" owner=root group=root
  when: not is_local
  tags: ssh-keys
