---

- name: "Get User Information"
  getent:
    database: passwd
    key:      "{{ user_key.username }}"

- name: "Build Information"
  set_fact:
    authkeys_file: "{{ user_key.authkeys_file | default(ssh_authkeys_files | first) | authfile_replace(getent_passwd) }}"
    is_local:     "{{ user_key.authkeys_file | default(ssh_authkeys_files | first) | is_local_path }}"

- name: "Authorize Key"
  become_user: "{{ user_key.username }}"
  authorized_key:
    user:  "{{ user_key.username }}"
    state: "{{ user_key.state | default(omit) }}"
    key:   "{{ lookup('file', user_key.key_file) }}"
    path:  "{{ authkeys_file }}"
    key_options: "{{ user_key.key_options | default(omit) }}"
    manage_dir: no

- name: "Set Ownership for Global File"
  file: path="{{ authkeys_file }}" owner=root group=root
  when: not is_local
