---

- set_fact:
    known_hosts_file: "{{ user_known.target_file | default(ssh_knownhosts_files | first) }}"

- name: "SSH User Directory"
  file:
    path:   "{{ known_hosts_file | dirname }}"
    state:  directory
    mode:   '0700'
    seuser: system_u
    serole: object_r
    setype: ssh_home_t

- name: "Acknowledge Host"
  known_hosts:
    state: "{{ item.state | default(omit) }}"
    name:  "{{ item.name }}"
    path:  "{{ known_hosts_file }}"
    key:   "{{ item.name }} {{ lookup('file', item.key_file) }}"
  with_items:
   - "{{ user_known.hosts }}"