---
# # # # #  Local Users  # # # # #

- name: "Require Correct Linux Distribution"
  assert:
    that: (ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_version | version_compare('6.0.0', '>=')) or
          (ansible_distribution == 'Debian'             and ansible_distribution_version | version_compare('7.0.0', '>=')) or
          (ansible_distribution == 'Ubuntu'             and ansible_distribution_version | version_compare('14.0.0', '>='))
    msg:  "This Linux distribution '{{ ansible_distribution }} {{ ansible_distribution_version }}' is not supported by the role."
  tags: ssh-keys

- name: "Host Keys Management"
  include: host_key.yml
  with_items:
   - "{{ ssh_host_keys | default([]) }}"
  loop_control:
    loop_var: host_key
  when: host_key.key_file is defined or
        host_key.key_content is defined
  tags: ssh-keys

- name: "User Keys Management"
  include: user_key.yml
  with_items:
   - "{{ ssh_user_keys | default([]) }}"
  loop_control:
    loop_var: user_key
  when: user_key.key_file is defined or
        user_key.key_content is defined
  tags: ssh-keys

- name: "Known Hosts File"
  become_user: "{{ user_known.username }}"
  include: known_hosts.yml
  with_items:
   - "{{ ssh_known_hosts | default([]) }}"
  loop_control:
    loop_var: user_known
  when: user_known.key_file is defined or
        user_known.key_content is defined
  tags: ssh-keys

- name: "Authorized Keys File"
  include: auth_key.yml
  with_items:
   - "{{ ssh_authorized_keys | default([]) }}"
  loop_control:
    loop_var: user_key
  when: user_key.key_file is defined or
        user_key.key_content is defined
  tags: ssh-keys
